flowchart TD
  Start --> Customer_Places_Order
  Customer_Places_Order --> Restaurant_Receives_Order
  Restaurant_Receives_Order --> Prepare_Food
  Prepare_Food --> Deliver_Food
  Deliver_Food --> Customer_Receives_Food
  Customer_Receives_Food --> End
